//all headers in one convenient file to simplify .cpp header references

#include "GlobalDefs.h"
#include "DefaultParams.h"
#include "ZhengModel.h"
#include "Neuron.h"
#include "Compartment.h"
#include "Channel.h"
#include "Synapse.h"
#include "Sensor.h"
#include "RunPage.h"
#include "NeuronPage.h"
#include "DisplayPage.h"
#include "TabCtrls.h"
#include "PlotsDialog.h"
#include "ZhengModelDoc.h"
#include "ZhengModelView.h"
#include "ChildFrm.h"
#include "MainFrm.h"
#include "GlobalFncs.h"
#include "Mark_math.h"
#include "math.h"